steps:
  - name: "gcr.io/cloud-builders/mvn"
    args: ["-D", "skipTests", "clean", "package"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/java-play', '.']
    images: ['gcr.io/$PROJECT_ID/java-play']